services:
  mongo1:
    image: mongo:6
    container_name: mongo1
    ports:
      - "27017:27017"  # Expose to host
    volumes:
      - ./docker/mongo1:/data/db
    networks:
      - mongo-cluster
    command: --replSet rs0 --bind_ip_all

  mongo2:
    image: mongo:6
    container_name: mongo2
    ports:
      - "27018:27017"  # Expose to host
    volumes:
      - ./docker/mongo2:/data/db
    networks:
      - mongo-cluster
    command: --replSet rs0 --bind_ip_all

  mongo3:
    image: mongo:6
    container_name: mongo3
    ports:
      - "27019:27017"  # Expose to host
    volumes:
      - ./docker/mongo3:/data/db
    networks:
      - mongo-cluster
    command: --replSet rs0 --bind_ip_all

networks:
  mongo-cluster:
    driver: bridge
